# Generated by Django 5.1.7 on 2025-03-19 03:07

import tracker.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_historicalscanevent_scanevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=tracker.utils.bundle_qr_image_upload_path),
        ),
        migrations.AddField(
            model_name='historicalbundle',
            name='qr_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalmaterialpiece',
            name='qr_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialpiece',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=tracker.utils.material_qr_image_upload_path),
        ),
    ]
