# Generated by Django 5.1.7 on 2025-03-19 03:13

import common.fields
import tracker.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bundle_qr_image_historicalbundle_qr_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='qr_image',
            field=common.fields.OptimizedImageField(blank=True, null=True, upload_to=tracker.utils.bundle_qr_image_upload_path),
        ),
        migrations.AlterField(
            model_name='materialpiece',
            name='qr_image',
            field=common.fields.OptimizedImageField(blank=True, null=True, upload_to=tracker.utils.material_qr_image_upload_path),
        ),
    ]
